- op: replace
  path: /spec/rules/0/host
  value: dev.producer.shakar.tech
- op: add
  path: /spec/tls
  value:
    - hosts:
        - dev.producer.shakar.tech
      secretName: lets-encrypt-dev.producer.shakar.tech
- op: add
  path: /metadata/annotations
  value:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
