resources:
- ../../base
patches:
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: rmq-test-nest-producer

commonLabels:
  app: dev-rmq-test-nest-producer
namespace: dev
configMapGenerator:
- behavior: merge
  literals:
  - ENV=dev
  name: rmq-test-nest-producer
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 5h4k4r/rmq-test-nest-producer
  newName: 5h4k4r/rmq-test-nest-producer
  newTag: 200c40abd4da997ff60a570832eb15985e564cee
