- op: replace
  path: /spec/rules/0/host
  value: producer.shakar.tech
- op: add
  path: /spec/tls
  value:
    - hosts:
        - producer.shakar.tech
      secretName: prod-tls
- op: add
  path: /metadata/annotations
  value:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
