resources:
  - ../../base
patches:
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: rmq-test-nest-producer

commonLabels:
  app: prod-rmq-test-nest-producer
namespace: prod
configMapGenerator:
  - behavior: merge
    literals:
      - ENV=prod
    name: rmq-test-nest-producer
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: 5h4k4r/rmq-test-nest-producer
    newName: 5h4k4r/rmq-test-nest-producer
    newTag: 4b9a7c4c69e18416d5dc10b841e75e537fdb605b
